default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'db' %>
development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'railpro_development' %>
test:
  <<: *default
  database: railpro_test
production:
  <<: *default
  password: <%= ENV['MYSQL_DATABASE'] || 'ralipro_production' %>
